language: php

sudo: true

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 5.6
 - 7.1

matrix:
 fast_finish: true
 exclude:
    # MySQL - we do not use the database to store data
    - env: DB=mysqli   PHPUNIT=false    INSTALL=false   CITEST=false
      php: 5.6
    - env: DB=mysqli   PHPUNIT=false    INSTALL=false   CITEST=false
      php: 7.1
 
env:
 global:
  - MOODLE_BRANCH=MOODLE_32_STABLE
  - MOODLE_BRANCH=master
 matrix:
  - DB=mysqli
    
before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  #- moodle-plugin-ci csslint 
  #- moodle-plugin-ci shifter
  #- moodle-plugin-ci jshint
  - moodle-plugin-ci validate
  #- moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
