name: Tests

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-18.04

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        options: --health-cmd="pg_isready" --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432
      mariadb:
        image: mariadb
        env:
          MYSQL_USER: 'root'
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
        options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3
        ports:
          - 3306:3306

    strategy:
      fail-fast: false
      matrix:
        moodle-branch: ['master', 'MOODLE_311_STABLE', 'MOODLE_310_STABLE', 'MOODLE_39_STABLE']
        php: ['7.4', '7.3']
        database: ['pgsql', 'mariadb']

    name: ${{ matrix.moodle-branch }}  php ${{ matrix.php }}  ${{ matrix.database }}

    steps:
      - name: checkout plugin
        uses: actions/checkout@v2
        with:
          path: this-plugin

      - name: setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, pgsql, mysqli, gd, zip

      - name: composer
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
          echo $(cd ci/bin; pwd) >> $GITHUB_PATH
          echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
          sudo locale-gen en_AU.UTF-8

      - name: install Moodle
        run: moodle-plugin-ci install --db-host=127.0.0.1 --plugin this-plugin
        env:
          DB: ${{ matrix.database }}
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}

      - name: phplint
        run: moodle-plugin-ci --ansi phplint

      - name: phpcpd
        run: moodle-plugin-ci --ansi phpcpd

      - name: phpmd
        run: moodle-plugin-ci --ansi phpmd

      - name: codechecker
        run: moodle-plugin-ci --ansi codechecker

      - name: validate
        run: moodle-plugin-ci --ansi validate

      - name: savepoints
        run: moodle-plugin-ci --ansi savepoints

      - name: mustache
        run: moodle-plugin-ci --ansi mustache

      - name: grunt
        run: moodle-plugin-ci --ansi grunt

      - name: phpunit 
        run: vendor/bin/phpunit --configuration report/comments/phpunit.xml --coverage-clover coverage/lcov.info --colors --testsuite report_comments_testsuite
        working-directory: moodle

      - name: firefox
        run: moodle-plugin-ci behat --ansi
      
      - name: chrome
        run: moodle-plugin-ci behat --ansi --profile chrome

      - name: admin bookmarks
        run: php admin/tool/behat/cli/run.php --tags=@block_admin_bookmarks
        working-directory: moodle

      - name: privacy
        run: vendor/bin/phpunit --colors --no-coverage --testsuite tool_dataprivacy_testsuite,tool_policy_testsuite,core_privacy_testsuite
        working-directory: moodle

      - name: coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token:  ${{ secrets.github_token }}
          flag-name: run-${{ matrix.moodle-branch }}-php${{ matrix.php }}-${{ matrix.database }}
          parallel: true

  finish:
    needs: ci
    runs-on: ubuntu-18.04
    steps:
    - name: coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token:  ${{ secrets.github_token }}
        parallel-finished: true
